import brandJson from "./brand.json";

/**
 * Everything that makes this site one company's rather than another's —
 * name, wordmark, location line, page title, headlines and button copy —
 * apart from the business data in seed.json (services, prices, contact
 * details, reviews) and the photos in images.ts.
 *
 * brand.json is edited by hand. seed.json is regenerated by
 * scripts/build-seed.mjs, so brand copy lives here where a rerun can't
 * overwrite it. Reusing the site for another company starts with this file.
 *
 * Code outside the marketing pages (the theme, the admin) imports it as
 * `@/data/brand`: the `@/data` barrel also carries seed.json, and going
 * through it would put that into every chunk.
 */
export const brand = brandJson;
export type Brand = typeof brandJson;

/**
 * Fills `{placeholders}` in a brand.json template, so copy that mixes in data
 * ("{years}+ years…") stays editable as one sentence. Unknown placeholders are
 * left as written, which makes a typo visible on the page instead of blank.
 */
export function fillTemplate(template: string, values: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (match, key: string) => (key in values ? String(values[key]) : match));
}
